<div class="container">
  <div class="row">
    <div class="d-flex justify-content-between">
      <h1>Equipments</h1>
      <div class="w-10 align-content-center">
        <a href="<?php echo route('equipments.new') ?>" type="submit" class="btn btn-primary btn-block">New</a>
      </div>
    </div>
    <div class="row mt-1 equipment-list">
      <?php foreach ($equipments as $item): ?>
        <div class="col-md-6 my-2">
          <div class="">
            <div class="card mb-3 equipment-item border-opacity-25" style="max-width: 540px;">
              <div class="row">
                <div class="col card-img-container">
                  <img src="<?= $item['image_path'] ?>" class="card-img" alt="...">
                </div>
                <div class="col">
                  <div class="card-body">
                    <h5 class="card-title"><?= $item['name'] ?></h5>
                    <p class="card-text"><?= $item['description'] ?></p>
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  </div>