<div class="container">
  <div class="row">
    <div class="d-flex justify-content-between">
      <h1>Equipments</h1>
      <div class="w-10 align-content-center">
        <a href="<?php echo route('equipments.new') ?>" type="submit" class="btn btn-primary btn-block">New</a>
      </div>
    </div>
    <div class="row mt-1 equipment-list">
      <?php if (empty($equipments)) : ?>
        <div class="col-md-12">
          <div class="alert alert-warning mt-3" role="alert">
            No equipments found.
          </div>
        </div>
      <?php endif; ?>
      <?php foreach ($equipments as $item): ?>
        <div class="col-md-6 my-2">
          <div class="card mb-3 equipment-item border-opacity-25" style="max-width: 540px;">
            <div class="row">
              <div class="col card-img-container">
                <img src="<?= $item->image_path ?>" class="card-img" alt="...">
              </div>
              <div class="col position-relative">
                <div class="card-body">
                  <h5 class="card-title"><?= $item->name?></h5>
                  <p class="card-text mb-1">
                    <medium class="text-muted"><?= $item->category ?></medium>
                  </p>
                  <p class="card-text">
                    <big class="text-muted">$ <?= $item->rental_price ?>/day</big>
                  </p>
                </div>
                <div class="equipment-card-actions position-absolute">
                  <a href="<?= route('maintenances.index', ['id' => $item->id]) ?>" class="btn btn-link">
                    <i class="bi bi-wrench"></i>
                  </a>
                  <a href="<?= route('equipments.show', ['id' => $item->id]) ?>" class="btn btn-link">
                    <i class="bi bi-search"></i>
                  </a>
                  <a href="<?= route('equipments.edit', ['id' => $item->id]) ?>" class="btn btn-link">
                    <i class="bi bi-pencil"></i>
                  </a>
                  <form action="<?= route('equipments.destroy', ['id' => $item->id]) ?>" method="POST" class="m-0">
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-link"><i class="bi bi-trash3"></i></button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  </div>