<form action="/login" method="POST">
    <div class="form-group mb-3">
        <label for="user_email" class="form-label">Email</label>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1"><i class="bi bi-envelope-at"></i></span>
            <input id="user_email" class="form-control" placeholder="Email" type="text" class="form-control" name="user[email]" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1">
        </div>
    </div>
    <div class="form-group mb-3">
        <label for="user_password" class="form-label">Password</label>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1"><i class="bi bi-key"></i></span>
            <input id="user_password" class="form-control" placeholder="Password" type="password" class="form-control" name="user[password]" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
        </div>
    </div>
    <div class="d-grid w-50 mt-4 mx-auto">
        <input type="submit" class="btn btn-primary btn-block" value="Submit">
    </div>
</form>