<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ERMS</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body>
    <div class="container d-flex justify-content-center position-fixed start-50 translate-middle">
        <div class="w-50">
            <?php require '_flash_message.phtml'; ?>
        </div>
    </div>
    <nav class="nav navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><span class="text-primary fs-1">ERMS</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <?php if ($this->current_user && $this->current_user->isAdmin()) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Reports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<?php echo route("equipments.index") ?>">Equipments</a>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->current_user && !$this->current_user->isAdmin()) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Equipments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Reservations</a>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->current_user) : ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Account
                            </a>
                            <ul class="dropdown-menu">
                                <p class="dropdown-item"><?php echo $this->current_user->email ?></p>
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item text-danger" href="<?php echo route('users.logout') ?>">Logout</a></li>
                            </ul>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Equipments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="<? echo route('users.login') ?>">Login</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>

    <div class="view">
        <?php require $view ?>
    </div>
</body>

</html>