<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ERMS</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/login.css">
</head>

<body class="d-flex align-items-center justify-content-center">

    <div class="card p-6 login">
        <div class="card-body">
            <div class="card-title">

                <?php require '_flash_message.phtml'; ?>

                <div class="justify-content-center d-flex m-3 mb-4 border-bottom border-primary">
                    <i class="bi bi-building-gear h1 text-primary"></i>
                    <h2 class="text-center ms-2 text-primary">ERMS</h2>
                </div>
                <h4 class="text-center mb-3">
                    Login
                </h4>

                <?php require $view ?>
            </div>
        </div>

    </div>

</body>

</html>